# Generated by Django 5.2.8 on 2025-11-27 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Single_Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=200)),
                ('meal_description', models.TextField(blank=True)),
                ('meal_type_choice', models.CharField(max_length=50)),
                ('meal_id', models.IntegerField()),
                ('recipe_link', models.URLField(blank=True, null=True)),
                ('calories', models.FloatField(default=0.0)),
                ('fats', models.FloatField(default=0.0)),
                ('carbs', models.FloatField(default=0.0)),
                ('sugar', models.FloatField(default=0.0)),
                ('sodium', models.FloatField(default=0.0)),
                ('protien', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Meal_Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('meals', models.ManyToManyField(related_name='mealplans', to='WellFed_App.single_meal')),
            ],
        ),
    ]
