# Generated by Django 5.2.7 on 2025-10-21 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WellFed_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='single_meal',
            name='meal_type_choice',
            field=models.CharField(default='lunch', max_length=50),
            preserve_default=False,
        ),
    ]
