# Generated by Django 5.2.8 on 2025-11-27 03:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WellFed_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal_plan',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='single_meal',
            name='meal_date',
            field=models.DateField(default=None),
        ),
    ]
