# Generated by Django 5.2.8 on 2025-11-27 03:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WellFed_App', '0002_meal_plan_date_created_single_meal_meal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='single_meal',
            name='meal_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
