# Generated by Django 5.2.8 on 2025-11-27 03:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WellFed_App', '0003_alter_single_meal_meal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal_plan',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
