# Generated by Django 5.2.8 on 2025-11-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WellFed_App', '0004_alter_meal_plan_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='single_meal',
            name='meal_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='single_meal',
            name='meal_type_choice',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack'), ('Dessert', 'Dessert'), ('Beverage', 'Beverage')], default='Breakfast', max_length=20),
        ),
    ]
